### ISSUE TITLE
Any working example of IsolatedTemplateService with a sandbox domain?

### ISSUE THREAD

**Issue by imran1231** [Antaris/RazorEngine#144]
I have tried a huge number of combination sandbox domain with IsolatedTemplateService but nothing works? Only works if I set

```
var permissionSet = new PermissionSet(PermissionState.Unrestricted);
```

Any working example/sample will be appreciated? I am using RazorEngine 3.2.0.0

**Comment by chrfin** [comment]
A little late, but I now finally had some time to try this out:
If the base class uses `Task` like the following:

    public abstract class BaseClass
    {
        public Task ExecuteAsync() { Execute();  return Task.FromResult(0); }
        public abstract void Execute();
    }
and in another library you inherit that like:

    public class SubClass : BaseClass
    {
        public override void Execute() { var str = "Hello world!"; }
    }

only the library containing the `ExecuteAsync` has a TypeRef to `Task`, but the second one only has a TypeRef to `BaseClass` => for cases like mine you can still prohibit the usage of `Task` even if the template base class uses them...

**Comment by matthid** [comment]
Did you try to use Razor4 (4.x-beta)? Razor will just override the Task based method and therefore you have a Task reference. Of course you can work around that by allowing this one instance and so on.  What I'm trying to say is that it is error prone and I don't see the value :). Isolation gives you a more isolated environment to work with, without introducing strange limitations.

**Comment by chrfin** [comment]
No, I did not try it with the actual Razor 4. And I am not planning to use such a feature as an alternative to isolation, but additional to it as I want "all three layers of security/isolation":

* Isolated AppDomain with restricted permission-set
* Forbidden types, especially threads and Tasks to prohibit "background actions" and Activator to prohibit creating types via reflection
* Render timeout to prevent endless loops

I'm using Razor-templates for user-generated content (e.g. mail-templates in my CMS) so "simple isolation" is not secure enought IMO. Because of that I also do not need `async`/`await` in my templates as there is no IO which would benefit from it so I could easily work around an async-execute with an "intermediate template" built like my test-app.

BUT I completely understand if you do not want to introduce such a "strange" limitation logic into the main library. I try to find the time over the next few weeks (hopefully) to finally propose you a pull-request for the timeout-feature. Maybe I also find a way to make my third limitation "pluggable" so I can add it "externally" just for my project...

**Comment by chrfin** [comment]
Just forked the repo to take a look at it and I am not sure where exactly I should look at: Can you point me to the place/class where at the moment or in future the compilation will happen?

**Comment by matthid** [comment]
Ah now I see, as an additional restriction it makes more sence. 

#### Thread / Task
> BUT I completely understand if you do not want to introduce such a "strange" limitation logic into the main library.

It's actually quite the opposite, if such a thing is possible (If we need another dependency I think the best would be to add another library to this repository and another nuget package). What I'm questioning however is: Is there is a way to make this happen reliable? I still don't think so. Especially with future version of the Razor parser in mind (Razor4).

* Forbidden types, especially threads and Tasks to prohibit "background actions" and Activator to prohibit creating types via reflection

The problem is you can't even guarantee to get your initial Thread back:

> The thread is not guaranteed to abort immediately, or at all.

From https://msdn.microsoft.com/en-us/library/ty8d3wta%28v=vs.110%29.aspx

Because we talking about security here we must ensure a possible attacker can't ever use such corner cases in any way. What about Garbage collection and the finalizer? Those happen in another Thread, so the attacker can possibly use it as their background thread and viola there is your background operation :) (I agree that it might be difficult to get there, but Razor 4 gives a lot more potential which I didn't look into)

I'd love to be proven wrong, but it looks there are a lot of attack vectors to consider (maybe to much to handle all). And Razor4 complicates the situation dramatically!

It might be a lot of easier to implement what you need with process encapsulation...

### Timeout

I would accept the timeout in the core library, because it is not really a security feature, but something people might want for various other reasons. And we don't need a new external dependency.

### Code:
To get started I would take a look into the compilation process: https://github.com/Antaris/RazorEngine/tree/master/src/source/RazorEngine.Core/Compilation
After everything is compiled the Assembly is loaded (the result of this process). So maybe after loading the assembly (or before?) is a good time to check it.
It always happens here:
https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Compilation/CompilerServiceBase.cs#L206

Depending on the compiler you use: 
 * https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Compilation/DirectCompilerServiceBase.cs#L256 (CodeDOM)
 * https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core.Roslyn/RoslynCompilerServiceBase.cs#L238 (Roslyn)

The reason you don't have a general location to access the Assembly-location is that I hope to get support for dynamic Assemblies in Roslyn (but I'm not sure if this is happening now that they removed this feature: please see https://github.com/Antaris/RazorEngine/issues/239 and vote for http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6120992-support-for-collectible-assemblies)

For Timeout you need to look at: https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/RazorEngineCore.cs#L132
Every running template is called through this `RunTemplate` method. The only other way is if the user calls ITemplate.Run itself, but this way of using the API is not encouraged (obsolete) and doesn't work in connection with Isolation

**Comment by chrfin** [comment]
Thanks for your input: I see I need to investigate more on that topic...
But I'll be looking at the timeout possibilities.

P.S.: I do not need "absolute security" as the templates in question can't be edited by "everyone", but just by users of the CMS which have the appropriate rights, so its more a question of how far I trust such users. But I may will also look into process encapsulation instead of just an isolated AppDomain - but I need to check the performance for that in comparisson to just an isolated AppDomain...
