### ISSUE TITLE
Dynamic Proxies Chuck an Exception

### ISSUE THREAD

**Issue by DavidRogersDev** [Antaris/RazorEngine#173]
Dynamic Proxies generated by EF6 throw the following exception:

_Unable to compile template. The type or namespace name 'DynamicProxies' does not exist in the namespace 'System.Data.Entity' (are you missing an assembly reference?)_

_Other compilation errors may have occurred. Check the Errors property for more information._

This is not so good if you want to use lazy loading.

**Comment by b2k** [comment]
I am seeing this in one of my templates as well. Please reopen this, because dynamic proxies are generated by EntityFramework when doing lazy loading of entities. The expected behavior is that they will resolve automatically  when the proxy is accessed. This is how razor files function out-of-the box. It is reasonable to assume that the Razor Engine would function in the same manner.

In the attached template, all of my models are referenced by the included using statement. See line 38 of the attached template_error.txt file. It seems odd that RazorEngine is building a subclass of the dynamic proxy for my model, instead of the type specified in the @model statement.

[ReadyToBuy.template.txt](https://github.com/Antaris/RazorEngine/files/9801762/ReadyToBuy.template.txt)
[template_error.txt](https://github.com/Antaris/RazorEngine/files/9801763/template_error.txt)

**Comment by b2k** [comment]
> It seems like a assembly reference is missing for the template.
> 
> You can fix that in two ways: The first is to just add the missing reference and make sure the assembly is loaded calling the Razor methods (for example by calling typeof()). If you do not want to add that reference you can use a new API and specify the references of the template manually. You need to use the current master branch and set the ReferenceResolver property within your RazorEngine configuration. See also: http://matthid.github.io/RazorEngine/#Set-a-resolver. Please reopen if this doesn't fix your issue.

The documentation on using ReferenceResolvers isn't very helpful. Is the ReferenceResolver replacing the existing behavior or supplementing it? An example would be helpful.
