### ISSUE TITLE
Support razor syntax for plain text

### ISSUE THREAD

**Issue by mmiller678** [Antaris/RazorEngine#227]
The following razor template::

@Model.SomeProperty@:Suffix

Results in the following exception:

System.TypeAccessException: Attempt by security transparent method 'RazorEngine.Templating.TemplateParsingException..ctor(System.Web.Razor.Parser.SyntaxTree.RazorError)' to access security critical type 'System.Web.Razor.Parser.SyntaxTree.RazorError' failed.

Assembly 'RazorEngine, Version=3.5.0.0, Culture=neutral, PublicKeyToken=9ee697374c7e744a' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.

It appears the @: razor syntax is not supported - that is fine as long as its documented but the error makes it difficult to understand exactly what the issue is.  Ideally the syntax would be supported as it is in MVC or the error message would be clearer as to what the issue is.

**Comment by matthid** [comment]
Yes the security exception is a bug and I think it was fixed with 3.5.3 (https://www.nuget.org/packages/RazorEngine/3.5.3).
The TemplateParsingException (RazorError) is raised by the Razor Parser so it is either just invalid syntax or a bug in Razor itself.
If you are on .net40 you are using an outdated version of the parser (https://github.com/mono/aspnetwebstack/tree/master/src/System.Web.Razor) which is sadly no longer updated.
If you are on .net45 and use Razor 3.2.2 you should send a bug report to Razor instead (https://github.com/aspnet/Razor) .

If you get the same SecurityException on the latest RazorEngine version feel free to leave a comment and I will investigate this.

**Comment by matthid** [comment]
In short: The error message should improve after updating to the latest version.
