### ISSUE TITLE
Stylesheet

### ISSUE THREAD

**Issue by sync876** [Antaris/RazorEngine#230]
Is it possible to link an external stylesheet in the template? Example: `<head><link href="/Content/css/style.default.css" rel="stylesheet"></head>`

**Comment by matthid** [comment]
Why wouldn't it? And what does that have to do with RazorEngine?

**Comment by sync876** [comment]
Been trying to achieve that in a template that RazorEngine Parses. It doesn't seem to pull in the css file.

**Comment by matthid** [comment]
RazorEngine is a templating engine which gives you an API to transform Razor templates to strings, everything else is in your hand. The string/template you gave doesn't have any Razor annotations and will transform back to `<head><link href="/Content/css/style.default.css" rel="stylesheet"></head>`. Not sure what you are expecting.

**Comment by sync876** [comment]
I was expecting it to pull in the styles and apply it to the respective elements in-line pattern. Minimum expectation.

**Comment by matthid** [comment]
You should get started with Razor: http://www.asp.net/web-pages/overview/getting-started/introducing-razor-syntax-%28c%29

**Comment by advancedrei** [comment]
@matthid, there's no need to be mean. @sync876 is probably trying to use RazorEngine to generate emails, which is like 95% of the use case for the software. Not at all surprising that someone would ask this question.

@sync876, what you're looking for is [PreMailer.net](https://github.com/milkshakesoftware/PreMailer.Net). But that is something that you have to run AFTER you've parsed the template with RazorEngine.

HTH!

**Comment by matthid** [comment]
I just didn't understand what this question was all about and I was pretty sure that this was not RazorEngine related (that's why I closed it and posted the link). Thanks for clearing this up and showing an alternative.

@sync876 Sorry if my comment was mean, but that was not my intention. You can do something similar with custom Razor syntax and your own `TemplateBase<T>` class, but if you want that feature "out of the box" and with your unmodified html example you need to use other projects (as @advancedrei has mentioned).

**Comment by rharding123** [comment]
@matthid I am using RazorEngine to parse email templates and trying to include an external css stylesheet. Can razor engine load and parse external stylesheet? Is it possible to add a css template and compile it? 
for example:

in my code:
 Engine.Razor.AddTemplate("EmailStyle", File.ReadAllText(~/Content/Email.css));
 Engine.Razor.Compile("EmailStyle", null);

in my view 
    <head>
        <link rel="stylesheet" type="text/css"  href="~/Content/Email.css"  />
   </head>

**Comment by michaelscodingspot** [comment]
I'm using RazorEngine for emails and adding `<link rel="...">` isn't an option. I was able to add an external .css with a little workaround.
I have a  **styles.css** file in my solution in folder **EmailTemplates**, which is set "Copy to output folder: CopyIfNewer"
In my .cshtml file:
```
@{
    string codeBase = System.Reflection.Assembly.GetCallingAssembly().CodeBase;
    System.UriBuilder uri = new System.UriBuilder(codeBase);
    string path = System.Uri.UnescapeDataString(uri.Path);
    string assembly = System.IO.Path.GetDirectoryName(path);
    string stylePath = System.IO.Path.Combine(assembly, "EmailTemplates", "style.css");
    string styleContent = System.IO.File.ReadAllText(stylePath);
}
<style>
    @Raw(styleContent)
</style>

<div>
   <!-- your html content -->
</div>
```
Basically, I read the contents of **styles.css** and copy it to with **Raw** to the razor `<styles>` tag.
Note that **GetCallingAssembly()** should be used, since the assembly that's executing the parsing is RazorEngine. 
Also, you'll need to go to the CSS file's Properties (F4) in Visual Studio and have it copied to the output folder.
