### ISSUE TITLE
What happened to the TempalteManager ?

### ISSUE THREAD

**Issue by aviatrix** [Antaris/RazorEngine#245]
For the past 3 hours i've been trying to figure out how the heck can i just pass a view name/path to RazorEngine as i used to do, and make it spit out html. 

Now i have to hack my own TempalteManager and waste hours trying to figure out the API and how to load partials and layouts.
Why there is no default immplementation anymore?

**Comment by matthid** [comment]
Hm, can you give a code example of what exactly you think is now more difficult? Maybe I can then give you a hint of how to do that in the current version.

Besides that the old API should still be there, is it not working for you?

There is a default implementation in the Quick-start guide, you can just ignore `resolvetype` and `context` and have your familiar name resolution in `Resolve`. You can also ignore `AddDynamic` and leave it not implemented if all your templates are in files.

The reason the `TemplateManager` is now more "complex" is so that you can tell RazorEngine the file location as well (this will improve your debugging support a lot!). You now can tell RazorEngine to resolve Layouts and Includes differently (maybe you want to have them in different folders), but if you don't want or need those features just ignore them (see above).

But just in case here is a implementation taking the familiar resolve delegate:
```csharp
public class DefaultTemplateManager : ITemplateManager
{
    Func<string, string> resolver;
    public DefaultTemplateManager(Func<string, string> resolve) {
        resolver = resolve;
    }

    public ITemplateSource Resolve(ITemplateKey key)
    {
        // NOTE: no debugging support, because no file path!
        return new LoadedTemplateSource(resolver(key.Name), null);
    }

    public ITemplateKey GetKey(string name, ResolveType resolveType, ITemplateKey context)
    {
        return new NameOnlyTemplateKey(name, resolveType, context);
    }

    public void AddDynamic(ITemplateKey key, ITemplateSource source)
    {
        throw new NotImplementedException("dynamic templates are not supported!");
    }
}
```
Maybe you can now see the problem, you could pass a delegate to resolve the path instead, but I figured people would confuse those. Also what about in-memory templates where no file-path is available?

Hope this helps.

**Comment by axefrog** [comment]
I'm in agreement with aviatrix - I want to pass in a file path and have it render. Caching should be automatic, and should invalidate if the file changes. I imagine this would be the primary use case for most people. Having to roll your own template manager, try to figure out how to invalidate the cache when the file changes and so forth (I *still* haven't figured that one out) is way more than most people willl want to have to deal with. The file path itself should become the key. Having the user select a key just defers unnecessary decisions onto the developer. The flexibility is good, but people who don't need it (i.e. most people) should be able to call a single method with a file path and have everything else buried under the hood as implementation details. Note also that deciding whether to run, then compile, or just run, etc. is also an implementation detail that the developer should not have to think about if they don't care. Pass in a path, get a result. Under the hood, load and compile if it's not already cached, use the cached version if it already exists and the source file hasn't changed, or reload the file, recompile it and re-cache it if the source file has changed.

You've got a great library here; if you could just make that primary use case *easy* then it would be perfect.
