### ISSUE TITLE
Templates broken with Enum after Upgrading 

### ISSUE THREAD

**Issue by devteamexpress** [Antaris/RazorEngine#248]
I upgraded to the latest version of RazorEngine.

Now every template which contained an enum throws the exception 

Operator '==' cannot be applied to operands of type 'ActLike_IComparable_e3dd4669a2f74680b7644a37e5d99d74' and ImageState'

Anyone have any ideas?

**Comment by matthid** [comment]
Interesting. You apparently use `dynamic` and we wrap the model in an `RazorDynamicObject`, which means you probably use an anonymous class. That's why you have no instance of ImageState where you expect one.
`RazorDynamicObject` is designed to work across AppDomains (in case of Isolation). This means only some well known types can escape this wrapper (primitives, string and DateTime).
I would accept a pull request making this behavior more configurable. But I guess the easier solution for you is to not use an anonymous class.

If you want this feature take a look at https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Compilation/RazorDynamicObject.cs and https://github.com/Antaris/RazorEngine/blob/2b80b822bfa30ed34adca4b477ec63ae91864edf/src/source/RazorEngine.Core/Templating/DynamicWrapperService.cs#L71

**Comment by matthid** [comment]
Maybe we can even just try to detect enums, cast them to their primitive type and return that instead.

**Comment by matthid** [comment]
Ok we support that now in 3.6.2 because we now forward operators as well (and wrap their result). https://github.com/Antaris/RazorEngine/commit/ac2191be63f54bf11ef2d5b2ff7b8efb3f4056cc
