### ISSUE TITLE
UriFormatException when using RazorEngine 

### ISSUE THREAD

**Issue by max-kudosh** [Antaris/RazorEngine#249]
I have a class library project in my solution which uses the RazorEngine v 3.6.1.0 to generate emails.

I compile the layout view, then i compile the specific view that uses the layout and run the template to get html. Both layout and view are strongly typed ( view model type is derived from layout model type ).
Here is the code sample:

Engine.Razor.Compile(layoutAsString, layoutName, modelType); 
Engine.Razor.Compile(viewAsString, viewName, modelType);
Engine.Razor.Run(viewName, modelType, model);

All goes well when the mailer project is referenced from the console application.

But when the mailer is used from the ASP.NET MVC project (all the mailer code is the same, nothing is changed), the following exception is thrown at Engine.Razor.Run(viewName, modelType, model):

[UriFormatException: Invalid URI: The format of the URI could not be determined.]
   System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) +6675677
   System.Uri..ctor(String uriString) +20
   CompiledRazorTemplates.Dynamic.<>c__DisplayClass1.<Abs>b__0(TextWriter __razor_helper_writer) +126
   RazorEngine.Templating.TemplateWriter.ToString() +105
   RazorEngine.Templating.TemplateBase.WriteAttributeTo(TextWriter writer, String name, PositionTagged`1 prefix, PositionTagged`1 suffix, AttributeValue[] values) +461
   RazorEngine.Templating.TemplateBase.WriteAttribute(String name, PositionTagged`1 prefix, PositionTagged`1 suffix, AttributeValue[] values) +77
   CompiledRazorTemplates.Dynamic.RazorEngine_7471f227b49241c59f1e33073fc4984c.Execute() +1057
   RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context, TextWriter reader) +211
   RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context, TextWriter reader) +470
   RazorEngine.Templating.RazorEngineCore.RunTemplate(ICompiledTemplate template, TextWriter writer, Object model, DynamicViewBag viewBag) +168
   RazorEngine.Templating.RazorEngineService.Run(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag) +95
   RazorEngine.Templating.DynamicWrapperService.Run(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag) +125
   RazorEngine.Templating.RazorEngineServiceExtensions.Run(IRazorEngineService service, String name, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag) +82
   RazorEngine.Templating.<>c__DisplayClassa.<Run>b__9(TextWriter writer) +84
   RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter) +91
   RazorEngine.Templating.RazorEngineServiceExtensions.Run(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag) +178

Can you please point out the possible reason of such behavior?

Thanks

**Comment by matthid** [comment]
Out of my head this looks like the following: RazorEngine uses all currently loaded assemblies as reference for the compilation, so maybe this influences the compiled result in your situation. But without the specific template .cshtml (or the resulting .cs) code and the list of assemblies I cannot say for sure. You can get the list of loaded assemblies with `AppDomain.GetAssemblies`

With the improved debugging experience it should be possible to pinpoint this as well: Enable `Debug` in the RazorEngine configuration and try setting a breakpoint within your cshtml file (of course you need to use files and a TemplateManager instead of raw strings, but I would suggest that anyway).

If you cannot switch to template files you can still try to figure this out by setting a breakpoint on `Run`, getting the list of loaded assemblies (for example via the direct window) and inspect the generated assemblies with dotpeek (or ILSpy). Try to look into both situations and look what is different in the generated assembly files.

Let me know if this helps.

**Comment by matthid** [comment]
If the above doesn't help you can try to post a minimal repro (with exact steps) here so I can look into it.

**Comment by max-kudosh** [comment]
Thanks for a quick reply

Here you can find a list of assemblies for each case and files, that were generated by RazorEngine (compiled templates and dlls): https://github.com/max-kudosh/razor-engine-debug-info

The compiled views look the same to me. I'm going to take a look at the assemblies.

The issue has gone, when i removed System.Uri.Uri constructor call in the template.

**Comment by matthid** [comment]
I can't see anything suspicious, can you try to add some `Console.WriteLines` near the Uri constructor call and print out on what parameter it is failing? Did you check if the reason for the invalid string is the `BaseUrl` property? (maybe your own code behaves differently in a ASP.NET environment?)

**Comment by max-kudosh** [comment]
Yes, you are right.
The web project was missing an appSetting. It looks so obvious now.

Anyway, thanks for help and sorry for wasting your time.
