### ISSUE TITLE
RazorEngine 3.6.3 cannot convert from 'string' to 'RazorEngine.Templating.ITemplateKey

### ISSUE THREAD

**Issue by rodchenkov** [Antaris/RazorEngine#255]
Hi

I posted my issue here http://stackoverflow.com/questions/29261175/razorengine-3-6-3-cannot-convert-from-string-to-razorengine-templating-itempl

I have a problem with RazorEngine version 3.6.3 RazorEngine cannot convert from 'string' to 'RazorEngine.Templating.ITemplateKey

My code is below:

        var templateServiceConfiguration = new TemplateServiceConfiguration();
        templateServiceConfiguration.Namespaces.Add("System.Configuration");

        var body = string.Empty;

        using (var service = RazorEngineService.Create(templateServiceConfiguration))
        {
            body = service.RunCompile(emailTemplate.Body, emailTemplate.UniqueName, model: _model, modelType: null, viewBag: null);
        }
So this method service.RunCompile( what as first parameter ITemplateKey, but there also overloads of this method that must support my version.

Please, help.

**Comment by matthid** [comment]
Most are extension methods, did you try to add `using RazorEngine.Templating`?

**Comment by rodchenkov** [comment]
Solved using this RazorEngineServiceExtensions.RunCompile(service, emailTemplate.Body, emailTemplate.UniqueName, modelType: null, model: _model);

But I think this is not a good variant as I had to use such variant instead of using it as Extension

**Comment by matthid** [comment]
I cannot reproduce
```csharp
using RazorEngine.Templating

//...
            using (var service = RazorEngineService.Create(null))
            {
                body = service.RunCompile("", "", model: new object(), modelType: null, viewBag: null);
            }
```

works fine for me. Feel free to send me a testcase/sample app.

**Comment by ManfredLange** [comment]
We ran into a similar problem, and the issue was that the variable that we passed as first parameter was declared as `var`. Took us a while to realize that it was assigned an `int`. Hence the compile error. Once we changed the variable type to `string` the coding error was clear and the line with `RunCompile()` or in our case `AddTemplate()` was fine as well.

I thought I'd share this, also because it is one of the few cases that I think show a disadvantage of `var`, but more so that other encountering this problem can solve it faster for them.
