### ISSUE TITLE
Missing generic methods

### ISSUE THREAD

**Issue by litera** [Antaris/RazorEngine#261]
I'm just converting my code from the obsolete `Razor.Parse` to `Engine.Razor.RunCompile` and while we have to explicitly provide model type I wonder why aren't there any generic extension methods that would be like:

    RunCompile<TModel>(string template, string key, TModel model);

instead of

    RunCompile(string template, string key, Type modelType, object model);

This would automatically provide type info to the engine while we wouldn't have to (always) explicitly define it. Most of the time type inference would do just fine for us and for the odd cases when we'd want to specify some base type we'd explicitly provide generic type.

**Comment by matthid** [comment]
I tried to add them, however while testing there where several problems:

- The compiler often couldn't figure out the overload we want to use (ambiguous)
- `RunCompile<dynamic>` is obviously not working and people would probably open issues for it

So I decided against it, however it should be straightforward to provide them via a different name if really needed (eg. RunCompileGeneric) however with the obvious limitation of dynamic.

But I really think using `model.GetType()` is a better option than using type-inference and otherwise specifying the type exactly is probably a good idea considering the above. 

And by the way you can always use

```csharp
RunCompile(template, key, model: model);
```
as modelType defaults to `null = dynamic`.

**Comment by matthid** [comment]
I don't think this is as reasonable as I thought initially because of the added ambiguity
