### ISSUE TITLE
Memcached Caching Provider and Serialization Issue

### ISSUE THREAD

**Issue by rmeshksar** [Antaris/RazorEngine#278]
Hi,
I am trying to implement Memcached Caching Provider.
The issue is that Memcached expects objects to be serialized and when trying, I am getting this error:

Type 'RazorEngine.Templating.CompiledTemplate' in Assembly 'RazorEngine, Version=3.7.0.0, Culture=neutral, PublicKeyToken=9ee697374c7e744a' is not marked as serializable.

Any idea how I can achieve this?

**Comment by matthid** [comment]
Using Memcached sounds like a really nice idea!

It is a bit more work than simply serializing the `CompiledTemplate` instance. For example you should create the `ITemplateKey` instance by calling the current `ITemplateManager` and you don't need to cache the `ITemplateSource` if you don't want to. 

It's also not clear how the `TemplateAssembly` would be serialized. Therefore it's probably a good idea to copy the assembly file to a safe place and load it from there if needed (and only memcache the "safe" location). That's because RazorEngine will delete its temporary assembly files once the process closes.

I would recommend one of the following: 
 * Get the assembly-file from the `CompilationData` and copy it to a new location.
   Save everything else (the name of the FullType, ModelType and Source) in memcached
   When loading load the assembly file, load the type and create a new `ICompiledTemplate` instance

 * If you don't need the isolation feature you can save the assembly memory (byte[]) in memcached instead of copying the assembly file

 * If you need isolation you can save the assembly in memory as well but write it to a temporary file before loading it.

I think adding the serializable attribute would do more harm than good because it would break later while de-serializing, because of a `FileNotFoundException`. Or would it actually work somehow?

Does this help?

**Comment by rmeshksar** [comment]
Thanks matthid for quick response.
Actually I would like to try pre-compiling Razor files to external assemblies and load it from there.

I have not found any example to show how it can be done.

Would you please guide me to the correct path for doing this.

Thanks.

**Comment by matthid** [comment]
> I have not found any example to show how it can be done.

I'm not sure is somebody has actually done this before, but it should be doable.

> Would you please guide me to the correct path for doing this.

I think you are on the right track: You will need an `ICachingProvider` implementation.
 * `CacheTemplate`: The `ICompiledTemplate` instance should provide you with all the information required. Including the `CompilationData` property which contains the temp-path (the `.dll` file in there is the assembly file). Either save the raw bytes directly or make a safe copy somewhere and save the copied path. Additionally save the `TemplateType` and `ModelType` FullNames (the same template can be compiled multiple times for different models! Your caching must take that into consideration!)
 * `Typeloader`: The TypeLoader can be created like [this](https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/InvalidatingCachingProvider.cs#L46) and works via sideeffect by modifying the `IEnumerable` (so when `TryRetrieveTemplate` is called and you get a "new/unknown" assembly from memcached you add it to the `List` or whatever you like to use, I recommend a `ConcurrentBag`). 

 * `TryRetrieveTemplate`: Then you will need a new implementation of `ICompiledTemplate` (a new class) and return it via the `out` parameter. The `ICompilationData` property can now actually be null because it is for the caching layer and you don't need to set it when it already came from the cache. The `ITemplateSource` cannot be null but an implementation only returning empty strings should be fine (if you plan to cache the generated template csharp source code as well you can add it here and get improved error messages).

That should be all you need to do including all major pitfalls.
