### ISSUE TITLE
How to render a template from already created C# code

### ISSUE THREAD

**Issue by rmeshksar** [Antaris/RazorEngine#302]
Hi,
In our CMS, we have hundreds of cshtml files and on every web page, several of them are getting used. 
Also, on the same platform, we have about 30 sites which are hosted on separate app pools on IIS.
SO, now we are excperiencing performance issue since those Razor files should be compiled and cached per site/ per web server and cached in memory.
The fact is that those Razor files are not getting updated at run time. That is why I am thinking to create a T4 template to scan through the specific folders, find cshtml files and use Razor Engine to create the C# code and class which eventually will be compiled along with the application. In this case all razor files are compiled already and there won't be any performance hit at run time.

Now, How can I "Run" these classes and generate the final rendered output.

Also, I would like to pass the dataModel inside each Razor file with @model directive and skip passing the type in Run method. Is it possible?

I found a Visual Studio extension called RazorEngine Generator which has the similar concept but it is a forked version of the code. I prefer to use the released version of the RazorEngine.

Thanks.

**Comment by matthid** [comment]
I think it may be easier to precompile the templates to assemblies and embed them to the application. This way you could re-use the existing infrastructure (a custom ICachingProvider would just load the templates from the resources (or from the file-system)).

But your idea sounds very interesting as well, so here is how it works internally:
 - We create a ITemplate instance
 - Set some internal properties
 - Execute Run

Look here for 1-2: https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/RazorEngineCore.cs#L75
and here for 3: https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/RazorEngineCore.cs#L137

As you can see, some things change in the upcoming version (see the `#if`s) because Razor itself has some huge API changes. We try hard to keep our surface API constant, but as you are using the raw code you would be hit.
It may actually be possible to use the existing infrastructure with your solution as well, by implementing a ICachingProvider which always returns the current assembly and the correct type instance. You can then use the regular RazorEngine API from within your application (and actually change the strategy anytime).

Hope this helps.
