### ISSUE TITLE
Zeal/Dash package

### ISSUE THREAD

**Issue by Grawl** [Antaris/RazorEngine#321]
[Zeal](https://zealdocs.org/) is a free port of [Dash](https://kapeli.com/dash), an offline documentation browser. [Dash docset](https://kapeli.com/docsets) is a standard of documentation for Zeal and [DevDocs](http://devdocs.io/) too.

Will be cool to generate Razor docset for these very useful tools like Zeal and DevDocs.

**Comment by matthid** [comment]
I'm not sure what we can do here at RazorEngine. 
Make a Dash plugin? -> We should make a separate project
Use it four our documentation? -> We should add it to FSharp.Formatting instead, because then more people can use it!
Closing because I think this is not related to RazorEngine, but feel free to explain if I misunderstood your point.
