### ISSUE TITLE
Confused trying to use this for .cshtml files in class library

### ISSUE THREAD

**Issue by DOTang** [Antaris/RazorEngine#387]
I am trying to use this library for .cshtml in a class library to be used as email templates.  (1) How does one set the template to be a .cshtml file? All the examples in the documentation only show a plain text string for the template.

It looks like from the documentation,  (2) I should change the template manager to ResolvePathTemplateManager? If all of my templates are .cshtml files, would that be best? The ResolvePathTemplateManager constructor wants me to put in rootpath strings for the directories whre the templates are loaded. (3) How do I get the root path in a class library? At the moment they are being copied to the output directory as content. Does this mean that I can only reference templates in those directories when calling compile, addtemplate, or run? Can I only reference them by path, or can they still have a key? (4) Is it better to set it to an embedded resource or some other way?

Also is it a good idea for at the start of the app (global.asax for web.app or Main() for console app) to just do .AddTemplate() and .Compile() for all my templates so I can just call .Run or is that bad for some reason or another? 

I guess what are the best approaches and practices for my scenario? Sorry for so many questions, I feel like the documentation is maybe not as clear as it could be since, since there is many ways to use this.

**Comment by Joev-** [comment]
I hope that I can shed some light on this for you. I spent the best part of yesterday facing the same issues as you did, mainly due to the poor examples in the documentation. I came close to switching to DotLiquid, but would rather a common template syntax in our project.

I'll address your points in order, and share an example of how I handled integration in my project.

1. Create your `.cshtml` files as normal, in a directory of your choice. It is important that these become available at runtime so that the Razor template engine can reference them. The solution that I have currently is to set the build action of each `.cshtml` template file to `Content` and `Copy if newer`. For a class library, this will copy these files to the referencing project's binary output folder too. 

2. Use the [ResolvePathTemplateManager](https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/ResolvePathTemplateManager.cs). This will allow you to specify your templates by file name only. The configuration for my RazorEngineService is as follows:

     ```cs
    _templatePaths = new[] {
        "Email/Templates",
    };

    _templateServiceConfiguration = new TemplateServiceConfiguration {
        TemplateManager = new ResolvePathTemplateManager(_templatePaths)
    };
    _razorEngineService = RazorEngineService.Create(_templateServiceConfiguration);

    ```
Note that you may need a more complete path, I have only tested my solution so far with integration tests, which used 
    ```cs
    Path.Combine(new DirectoryInfo(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", "..")).FullName, "Integration", "EmailTemplates");`
    ```

3. See above. I do not see the purpose of a key when using file templates. I would assume the path is enough to create a good cache, though I am uncertain of this whole concept.

4. Embedded resources are a terrible idea and not maintainable at all. 

Finally, using the ResolvePathTemplateManager method, you should not need to add your templates at startup. However, what the best practice is for using `Run()`, `Compile()` or `RunCompile()` I do not know.

Hope that helps, and that the documentation can be updated with better examples. I had to do a lot of digging around to get things working.

**Comment by kellysalvage** [comment]
Or you can just load the files into a LoadedTemplateSource like this:

```
                var templateSource = new LoadedTemplateSource(File.ReadAllText(fullFileName), fullFileName);
                eturn Engine.Razor.RunCompile(templateSource, typeof(T) +"Template_" + name, typeof(T), model, null)
```

**Comment by DOTang** [comment]
Thanks a lot Joev, this is great. I was able to get it working using the default template manager, but the file path way seems better. Are you able to specify subdirectories under that root path then later when adding the template? Or do you have to include all subdirectories at the start in the templatePaths for the config?

**Comment by DOTang** [comment]
kelly, is there an advantage of that over just supplying the template as text like 

`File.ReadAllText(UserReminderMailMessageService.TemplatePath);`

It seems like that would be more performant since you are already doing that, but also an extra call to make it a template source? Or does the overload .Run that accepts the template as a string just call that anyway underneath?

**Comment by Joev-** [comment]
@DOTang 

Regarding 1:
According to the [source code](https://github.com/Antaris/RazorEngine/blob/master/src/source/RazorEngine.Core/Templating/ResolvePathTemplateManager.cs#L65) you should be able to specify the sub directory as part of your path later, though I have not tried it. 
I'm not sure on the performance of using `RunCompile` rather than up-front manually specifying and loading all templates. I am doing something similar to you, and loading my templates based on the class name of POCO models (which are subsequently then passed into the template). However this is passed directly in as the filename to `RunCompile`, which performs all the loading from the filesystem for me. I plan to manually specify all my subdirectories in the configuration in my constructor.

I am not in work right now, but off the top of my head, my usage was along the lines of this:

```cs
BuildEmailTemplate<TEmailModel>(TEmailModel emailData) {
    var templateName = typeof(TEmailModel).Name;
    templateName += ".cshtml";

    _razorEngineService.RunCompile(templateName, typeof(TEmailModel), emailData); 
}
```

**Comment by kellysalvage** [comment]
@DOTang Sorry for the late reply. The advantage to using templatesource is that it allows you to enable debugging ( see https://github.com/Antaris/RazorEngine#debugging)

**Comment by egdd** [comment]
Dear all,

To address the subdirectory Issue:

As Joev posted, it is possible to use your own implementation for _ITemplateManager_. There you can include e.g. subdirectories to all given roots, too. In order to achieve that the I ended up replacing  with my own implementation that can deal with subdirectories - the rest of the class is close to _ResolvePathTemplateManager_:

```
        public YourOwnResolvePathTemplateManager(IEnumerable<string> layoutRoots) {
            IList<string> layoutRootsWithSubdirectories = new List<string>() { };

            foreach(var layoutRoot in layoutRoots) {
                layoutRootsWithSubdirectories.Add(layoutRoot);
                foreach (var subDirectory in Directory.GetDirectories(layoutRoot)) {
                    layoutRootsWithSubdirectories.Add(Path.Combine(subDirectory, "\\"));
                }
            }

            this.layoutRoots = new ReadOnlyCollection<string>(new List<string>(layoutRootsWithSubdirectories));
        }
```

Code can improved, I guess, but you get the point. If this code is useful it could be included in the _ResolvePathTemplateManager_ as well? Maybe with a flag, to exclude and include subdirectories?

Greetings

Moor

**Comment by mikesigs** [comment]
@Joev- I am really curious about your point #4:
> Embedded resources are a terrible idea and not maintainable at all.

Can you provide some reason behind this comment? I am currently using embedded resources and find it to be a really nice way to manage my templates in a class library. But, your comment left me wondering if there are things I have not considered about this approach that might make it less desirable.

Thanks!

**Comment by Joev-** [comment]
Hi @mikesigs,

Apologies, but I do not recall what my line of thought was at the time I posted that comment. I'd be interested to hear how you are using embedded resources, I may have had a bad experience with them previously and am looking to change my view.

Cheers :)

**Comment by matthid** [comment]
> mainly due to the poor examples in the documentation. 

Sad to hear this. Glad you guys could help each other. A PR to improve the docs is of course always welcome!

Closing as I think the original issue is solved (feel free to continue the discussion)
