### ISSUE TITLE
Not compatible with Microsoft.AspNetCore.Razor 2.0.0

### ISSUE THREAD

**Issue by 0x53A** [Antaris/RazorEngine#486]
[Microsoft.AspNetCore.Razor 2.0.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Razor/2.0.0) only contains a netstandard2.0 dll with a few types:

![image](https://user-images.githubusercontent.com/4236651/30004746-4e3c5be8-90d5-11e7-8d89-105faa7aff70.png)

This obviously causes RazorEngine to crash.

I would suggest to change the reference to 1.0 <= x < 2.0 and/or inquire with the asp.net team if this was on purpose and where the types moved.

**Comment by nvivo** [comment]
While this is not resolved, I'm leaving this workaround if someone needs it.

I was able to keep RazorEngine working on my app after upgrading to aspnet core 2.0 by using [ILMerge-GUI](https://github.com/jpdillingham/ILMergeGUI) + [ILRepack](https://github.com/gluck/il-repack) to merge and internalize it's dependencies:

![image](https://user-images.githubusercontent.com/202449/30189078-5e4e6496-9408-11e7-96f1-b16c0eb4ce32.png)

Just remove the nuget reference and add the reference to the new file instead. Not perfect, but prevented me from downgrading a dozen projects due to a single dependency.

**Comment by hermanho** [comment]
It seems that a breaking changes had made.
https://github.com/aspnet/Announcements/issues/227

**Comment by mscrivo** [comment]
I've tried adding those 2 extra packages, but still getting this error:

> Exception="System.TypeLoadException" ExceptionDetail="System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Razor.Parser.ParserBase' from assembly 'Microsoft.AspNetCore.Razor, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

with RazorEngine 4.5.1-alpha001

**Comment by GetTaxSolutions** [comment]
We also have some problem. Will it be fixed soon?

**Comment by daviatorstorm** [comment]
![image](https://user-images.githubusercontent.com/4057612/34105862-a219925e-e3fe-11e7-8643-7641e12c1d83.png)

**Comment by conniey** [comment]
@daviatorstorm Hi, the reason you are getting that issue is because an ASP.NET Core application (netcoreapp2.0) does not support System.Configuration. If you used a full Framework ASP.NET application, it would resolve correctly.
The package currently available on NuGet.org does not run on .NET Core yet.

**Comment by conniey** [comment]
@0x53A Can you give me a repro of the issue you're having? I am able to get my package, built from #488 to run and work on my ASP.NET Full .NET Framework application.

**Comment by 0x53A** [comment]
@conniey I don't have a standalone repo, but will describe my use case a bit more:

* F# fsx script that uses RazorEngine to generate files from templates
* I added a reference to ``RazorEngine`` through paket
* ``Microsoft.AspNetCore.Razor`` is pulled in as an implicit dependency, no other Asp.net projects are used in this context.

Now the issue is that between 1.x and 2.x, most classes were removed from ``Microsoft.AspNet.Razor.dll``, as you can see in my first screenshot.

This causes a typeload exception at runtime.

I fixed the issue by pinning ``Microsoft.AspNetCore.Razor < 2.0`` in my paket.dependencies.

**Comment by conniey** [comment]
@0x53A Thanks for explaining the issue! I asked the ASP.NET team and when we move to .NET Core, I'll have to add those extra dependencies they mention here: https://github.com/aspnet/Razor/issues/1855#issuecomment-352846900

Your current workaround is what I applied to #488 for now.

**Comment by nvivo** [comment]
@matthid Any chance we can get a new release with this support?

**Comment by conniey** [comment]
@nvivo hey, I had looked into this when it was first mentioned. However, they've upgraded, deprecated, and made internal many classes that RazorEngine uses. So it'll be a huge undertaking. I can look into it more over the weekend but no promises.

**Comment by nvivo** [comment]
@conniey Right. I thought #488 was solving this issue, as it was closed by it. So, it's being abandoned for now?

**Comment by conniey** [comment]
@nvivo #488 explicitly says we should use a version _less than_ 2.0.0 for RazorEngine.  Adding support for Microsoft.AspNetCore.Razor 2.0.0 would be another issue

**Comment by nvivo** [comment]
Sorry, I didn't read all the PR, just saw it closed this one. My fault.
